In [ ]:
# Import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Read data into pandas dataframe
kick_data = pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter002.csv")
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter003.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter004.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter005.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter006.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter007.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter008.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter009.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter010.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter011.csv"))
kick_data = kick_data.append(pd.read_csv("/Users/Nicole/Documents/Kickstarter/Kickstarter012.csv"))

# Isolate relevant attributes
kick_data = kick_data.loc[:, ['backers_count','blurb','category','country', 'goal', 
                              'staff_pick', 'state', 'usd_pledged']]

# remove live entries as their final state is unknown
kick_data = kick_data[kick_data.state != 'live']

# remove rows with missing values
kick_data = kick_data.dropna()

# reset index for model-building and to remove duplicate values
kick_data = kick_data.reset_index(drop=True)

kick_data.tail()

In [ ]:
z = 32000

# feature variables
x_train = kick_data.loc[:z, ['backers_count','goal', 'staff_pick', 'usd_pledged']]
x_test = kick_data.loc[z:, ['backers_count','goal', 'staff_pick', 'usd_pledged']]
# response variable
y_train = kick_data.loc[:z, 'state'] 
y_test = kick_data.loc[z:, 'state']

In [34]:
from sklearn.linear_model import LogisticRegression
# logistic regression object
model = LogisticRegression()
# train model and check score
model.fit(x_train, y_train)
model.score(x_train, y_train)
# output equation coefficient and intercept
print('Coefficient: \n', model.coef_)
print('Intercept: \n', model.intercept_)
# predict output of test da
predicted= model.predict(x_test)

Coefficient: 
 [[ -7.26377980e-02  -2.59474210e-09   1.77424612e-03   2.01767481e-05]
 [ -2.35784846e-02   6.62866006e-07  -4.25628028e-05  -1.39767401e-05]
 [  2.38007492e-02  -2.88030591e-05   4.80411281e-05   6.52128221e-05]
 [ -5.73519093e-02  -3.96690950e-05  -3.35926683e-02   1.75624691e-05]]
Intercept: 
 [ -1.27445304e+00   6.51983148e-04  -7.51794766e-04  -2.71483044e+00]
